import { Stock } from '../types/types';

const initialStocks: Stock[] = [
  {
    name: 'Apple',
    symbol: 'AAPL',
    sector: 'Information Technology',
    investmentType: 'Stocks',
    marketCap: 2230,
    dividendYield: 0.5,
    maxDrawdown: 20,
    sharpe: 1.5,
    sterling: 1.2,
    ema50: 80,
    rsi: 60,
    stochastic: 70,
    lastPrice: 213.96,
    changePercent: -1.27,
    change: -2.75,
    open: 217.59,
    prevClose: 216.71,
    volume: 43.659,
    overview: 'Apple Inc. designs, manufactures, and markets mobile communication and media devices, personal computers, and portable digital music players.',
    recentNews: 'In the past month, Apple Corporation has made significant headlines, notably surpassing Apple to become the first chip company to hit a $3 trillion market cap.',
    comments: ['Great stock with promising future!', 'I\'m considering adding this to my portfolio.', 'Recent performance has been impressive.', 'Looking forward to seeing their next earnings report.'],
    previousRanking: 5,
    currentRanking: 4.2,
  },
  {
    name: 'Microsoft',
    symbol: 'MSFT',
    sector: 'Information Technology',
    investmentType: 'Stocks',
    marketCap: 1850,
    dividendYield: 1.0,
    maxDrawdown: 15,
    sharpe: 1.8,
    sterling: 1.3,
    ema50: 75,
    rsi: 65,
    stochastic: 68,
    lastPrice: 447.02,
    changePercent: -0.30,
    change: -1.37,
    open: 449.71,
    prevClose: 448.39,
    volume: 7.076,
    overview: 'Microsoft Corporation develops, licenses, and supports a wide range of software products, services, and devices.',
    recentNews: 'Microsoft has been focusing on expanding its cloud services and integrating AI technologies.',
    comments: ['Solid performance.', 'Great long-term investment.', 'Strong fundamentals.', 'Innovative technology.'],
    previousRanking: 3,
    currentRanking: 2.8,
  },
  {
    name: 'Amazon',
    symbol: 'AMZN',
    sector: 'Consumer Discretionary',
    investmentType: 'Stocks',
    marketCap: 1600,
    dividendYield: 0.0,
    maxDrawdown: 25,
    sharpe: 1.6,
    sterling: 1.1,
    ema50: 70,
    rsi: 55,
    stochastic: 65,
    lastPrice: 523.86,
    changePercent: 0.97,
    change: 5.02,
    open: 514.71,
    prevClose: 518.85,
    volume: 2.064,
    overview: 'Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally.',
    recentNews: 'Amazon has expanded its grocery delivery services and is investing heavily in logistics.',
    comments: ['Expanding services.', 'Strong market presence.', 'Great financials.', 'Solid performance.'],
    previousRanking: 6,
    currentRanking: 5.5,
  },
  {
    name: 'Alphabet',
    symbol: 'GOOGL',
    sector: 'Communication Services',
    investmentType: 'Stocks',
    marketCap: 1400,
    dividendYield: 0.0,
    maxDrawdown: 18,
    sharpe: 1.7,
    sterling: 1.2,
    ema50: 85,
    rsi: 62,
    stochastic: 72,
    lastPrice: 176.49,
    changePercent: -1.30,
    change: -2.33,
    open: 178.79,
    prevClose: 178.81,
    volume: 6.2,
    overview: 'Alphabet Inc. provides online advertising services and operates through Google and Other Bets segments.',
    recentNews: 'Alphabet is investing in AI research and development, and expanding its cloud computing services.',
    comments: ['Innovative company.', 'Strong growth potential.', 'Leader in AI technology.', 'Great investment.'],
    previousRanking: 4,
    currentRanking: 3.8,
  },
  {
    name: 'Facebook',
    symbol: 'FB',
    sector: 'Communication Services',
    investmentType: 'Stocks',
    marketCap: 900,
    dividendYield: 0.0,
    maxDrawdown: 22,
    sharpe: 1.4,
    sterling: 1.1,
    ema50: 78,
    rsi: 58,
    stochastic: 69,
    lastPrice: 354.78,
    changePercent: 0.50,
    change: 1.75,
    open: 352.34,
    prevClose: 353.03,
    volume: 2.789,
    overview: 'Facebook, Inc. operates as a social networking company worldwide.',
    recentNews: 'Facebook is focusing on expanding its virtual reality and augmented reality initiatives.',
    comments: ['Engaging platform.', 'Innovative features.', 'Growing user base.', 'Strong advertising revenue.'],
    previousRanking: 7,
    currentRanking: 6.5,
  },
  {
    name: 'Tesla',
    symbol: 'TSLA',
    sector: 'Consumer Discretionary',
    investmentType: 'Stocks',
    marketCap: 800,
    dividendYield: 0.0,
    maxDrawdown: 30,
    sharpe: 1.2,
    sterling: 1.0,
    ema50: 60,
    rsi: 50,
    stochastic: 55,
    lastPrice: 678.34,
    changePercent: -2.05,
    change: -14.18,
    open: 682.34,
    prevClose: 692.52,
    volume: 8.756,
    overview: 'Tesla, Inc. designs, develops, manufactures, and sells electric vehicles and energy storage products.',
    recentNews: 'Tesla is ramping up production of its new models and expanding its Gigafactories.',
    comments: ['Cutting-edge technology.', 'Strong growth potential.', 'Innovative company.', 'High volatility.'],
    previousRanking: 1,
    currentRanking: 2,
  },
];

export { initialStocks };
