// sp500Stocks.ts
export type Stock = {
  name: string;
  symbol: string;
  risk: number;
};
export const sp500Stocks = [
  { name: "3M", symbol: "MMM", risk: 30 },
  { name: "A. O. Smith", symbol: "AOS", risk: 25 },
  { name: "Abbott Laboratories", symbol: "ABT", risk: 20 },
  { name: "AbbVie Inc.", symbol: "ABBV", risk: 23 },
  { name: "Accenture", symbol: "ACN", risk: 18 },
  { name: "Activision Blizzard", symbol: "ATVI", risk: 27 },
  { name: "ADM", symbol: "ADM", risk: 15 },
  { name: "Adobe Inc.", symbol: "ADBE", risk: 22 },
  { name: "Advanced Micro Devices", symbol: "AMD", risk: 28 },
  { name: "AES Corporation", symbol: "AES", risk: 21 },
  { name: "Aflac", symbol: "AFL", risk: 19 },
  { name: "Agilent Technologies", symbol: "A", risk: 17 },
  { name: "Air Products & Chemicals", symbol: "APD", risk: 16 },
  { name: "Akamai Technologies", symbol: "AKAM", risk: 20 },
  { name: "Alaska Air Group", symbol: "ALK", risk: 23 },
  { name: "Albemarle Corporation", symbol: "ALB", risk: 24 },
  { name: "Alexandria Real Estate Equities", symbol: "ARE", risk: 18 },
  { name: "Align Technology", symbol: "ALGN", risk: 27 },
  { name: "Allegion", symbol: "ALLE", risk: 22 },
  { name: "Alliant Energy", symbol: "LNT", risk: 19 },
  { name: "Allstate", symbol: "ALL", risk: 20 },
  { name: "Alphabet Inc. (Class A)", symbol: "GOOGL", risk: 18 },
  { name: "Alphabet Inc. (Class C)", symbol: "GOOG", risk: 18 },
  { name: "Altria", symbol: "MO", risk: 23 },
  { name: "Amazon", symbol: "AMZN", risk: 25 },
  { name: "Amcor", symbol: "AMCR", risk: 16 },
  { name: "Ameren", symbol: "AEE", risk: 21 },
  { name: "American Airlines Group", symbol: "AAL", risk: 24 },
  { name: "American Electric Power", symbol: "AEP", risk: 20 },
  { name: "American Express", symbol: "AXP", risk: 17 },
  { name: "American International Group", symbol: "AIG", risk: 19 },
  { name: "American Tower", symbol: "AMT", risk: 20 },
  { name: "American Water Works", symbol: "AWK", risk: 18 },
  { name: "Ameriprise Financial", symbol: "AMP", risk: 17 },
  { name: "AmerisourceBergen", symbol: "ABC", risk: 21 },
  { name: "Ametek", symbol: "AME", risk: 22 },
  { name: "Amgen", symbol: "AMGN", risk: 24 },
  { name: "Amphenol", symbol: "APH", risk: 20 },
  { name: "Analog Devices", symbol: "ADI", risk: 18 },
  { name: "Ansys", symbol: "ANSS", risk: 22 },
  { name: "Aon", symbol: "AON", risk: 19 },
  { name: "APA Corporation", symbol: "APA", risk: 23 },
  { name: "Apple", symbol: "AAPL", risk: 20 },
  { name: "Applied Materials", symbol: "AMAT", risk: 22 },
  { name: "Aptiv", symbol: "APTV", risk: 21 },
  { name: "Arch Capital Group", symbol: "ACGL", risk: 18 },
  { name: "Archer-Daniels-Midland", symbol: "ADM", risk: 15 },
  { name: "Arista Networks", symbol: "ANET", risk: 21 },
  { name: "Arthur J. Gallagher & Co.", symbol: "AJG", risk: 17 },
  { name: "Assurant", symbol: "AIZ", risk: 18 },
  { name: "AT&T", symbol: "T", risk: 20 },
  { name: "Atmos Energy", symbol: "ATO", risk: 16 },
  { name: "Autodesk", symbol: "ADSK", risk: 22 },
  { name: "Automatic Data Processing", symbol: "ADP", risk: 19 },
  { name: "AutoZone", symbol: "AZO", risk: 24 },
  { name: "AvalonBay Communities", symbol: "AVB", risk: 21 },
  { name: "Avery Dennison", symbol: "AVY", risk: 17 },
  { name: "Axon Enterprise", symbol: "AXON", risk: 18 },
  { name: "Baker Hughes", symbol: "BKR", risk: 20 },
  { name: "Ball Corporation", symbol: "BALL", risk: 19 },
  { name: "Bank of America", symbol: "BAC", risk: 21 },
  { name: "Bank of New York Mellon", symbol: "BK", risk: 19 },
  { name: "Bath & Body Works, Inc.", symbol: "BBWI", risk: 20 },
  { name: "Baxter International", symbol: "BAX", risk: 18 },
  { name: "Becton Dickinson", symbol: "BDX", risk: 19 },
  { name: "Berkshire Hathaway", symbol: "BRK.B", risk: 10 },
  { name: "Best Buy", symbol: "BBY", risk: 21 },
  { name: "Bio-Rad Laboratories", symbol: "BIO", risk: 22 },
  { name: "Bio-Techne", symbol: "TECH", risk: 20 },
  { name: "Biogen", symbol: "BIIB", risk: 19 },
  { name: "BlackRock", symbol: "BLK", risk: 18 },
  { name: "Boeing", symbol: "BA", risk: 23 },
  { name: "Booking Holdings", symbol: "BKNG", risk: 20 },
  { name: "BorgWarner", symbol: "BWA", risk: 21 },
  { name: "Boston Properties", symbol: "BXP", risk: 19 },
  { name: "Boston Scientific", symbol: "BSX", risk: 18 },
  { name: "Broadcom Inc.", symbol: "AVGO", risk: 22 },
  { name: "Broadridge Financial Solutions", symbol: "BR", risk: 21 },
  { name: "Brown & Brown", symbol: "BRO", risk: 18 },
  { name: "Brown-Forman", symbol: "BF.B", risk: 17 },
  { name: "C.H. Robinson", symbol: "CHRW", risk: 20 },
  { name: "Cadence Design Systems", symbol: "CDNS", risk: 21 },
  { name: "Caesars Entertainment", symbol: "CZR", risk: 24 },
  { name: "Camden Property Trust", symbol: "CPT", risk: 18 },
  { name: "Campbell Soup", symbol: "CPB", risk: 17 },
  { name: "Capital One Financial", symbol: "COF", risk: 21 },
  { name: "Cardinal Health", symbol: "CAH", risk: 20 },
  { name: "CarMax", symbol: "KMX", risk: 22 },
  { name: "Carnival", symbol: "CCL", risk: 23 },
  { name: "Carrier Global", symbol: "CARR", risk: 20 },
  { name: "Catalent", symbol: "CTLT", risk: 21 },
  { name: "Caterpillar", symbol: "CAT", risk: 18 },
  { name: "Cboe Global Markets", symbol: "CBOE", risk: 20 },
  { name: "CBRE Group", symbol: "CBRE", risk: 18 },
  { name: "Celanese", symbol: "CE", risk: 19 },
  { name: "Centene Corporation", symbol: "CNC", risk: 17 },
  { name: "CenterPoint Energy", symbol: "CNP", risk: 21 },
  { name: "Ceridian", symbol: "CDAY", risk: 22 },
  { name: "CF Industries", symbol: "CF", risk: 20 },
  { name: "Charles River Laboratories", symbol: "CRL", risk: 21 },
  { name: "Charter Communications", symbol: "CHTR", risk: 18 },
  { name: "Chevron", symbol: "CVX", risk: 21 },
  { name: "Chipotle Mexican Grill", symbol: "CMG", risk: 23 },
  { name: "Chubb Limited", symbol: "CB", risk: 18 },
  { name: "Church & Dwight", symbol: "CHD", risk: 17 },
  { name: "Cigna", symbol: "CI", risk: 20 },
  { name: "Cincinnati Financial", symbol: "CINF", risk: 19 },
  { name: "Cintas", symbol: "CTAS", risk: 18 },
  { name: "Cisco Systems", symbol: "CSCO", risk: 20 },
  { name: "Citigroup", symbol: "C", risk: 21 },
  { name: "Citizens Financial Group", symbol: "CFG", risk: 18 },
  { name: "Clorox", symbol: "CLX", risk: 17 },
  { name: "CME Group", symbol: "CME", risk: 19 },
  { name: "CMS Energy", symbol: "CMS", risk: 18 },
  { name: "Coca-Cola Company", symbol: "KO", risk: 15 },
  { name: "Cognizant Technology Solutions", symbol: "CTSH", risk: 20 },
  { name: "Colgate-Palmolive", symbol: "CL", risk: 18 },
  { name: "Comcast", symbol: "CMCSA", risk: 19 },
  { name: "Conagra Brands", symbol: "CAG", risk: 20 },
  { name: "ConocoPhillips", symbol: "COP", risk: 21 },
  { name: "Consolidated Edison", symbol: "ED", risk: 18 },
  { name: "Constellation Brands", symbol: "STZ", risk: 20 },
  { name: "Constellation Energy", symbol: "CEG", risk: 22 },
  { name: "CooperCompanies", symbol: "COO", risk: 21 },
  { name: "Copart", symbol: "CPRT", risk: 20 },
  { name: "Corning", symbol: "GLW", risk: 19 },
  { name: "Corteva", symbol: "CTVA", risk: 20 },
  { name: "Costco Wholesale", symbol: "COST", risk: 15 },
  { name: "Crown Castle", symbol: "CCI", risk: 21 },
  { name: "CSX", symbol: "CSX", risk: 18 },
  { name: "Cummins", symbol: "CMI", risk: 19 },
  { name: "CVS Health", symbol: "CVS", risk: 18 },
  { name: "D.R. Horton", symbol: "DHI", risk: 22 },
  { name: "Danaher", symbol: "DHR", risk: 17 },
  { name: "Darden Restaurants", symbol: "DRI", risk: 19 },
  { name: "DaVita", symbol: "DVA", risk: 18 },
  { name: "Deere & Company", symbol: "DE", risk: 21 },
  { name: "Delta Air Lines", symbol: "DAL", risk: 24 },
  { name: "Dentsply Sirona", symbol: "XRAY", risk: 19 },
  { name: "Devon Energy", symbol: "DVN", risk: 23 },
  { name: "Dexcom", symbol: "DXCM", risk: 22 },
  { name: "Diamondback Energy", symbol: "FANG", risk: 21 },
  { name: "Digital Realty", symbol: "DLR", risk: 20 },
  { name: "Discover Financial", symbol: "DFS", risk: 19 },
  { name: "Dish Network", symbol: "DISH", risk: 23 },
  { name: "Disney", symbol: "DIS", risk: 20 },
  { name: "Dollar General", symbol: "DG", risk: 18 },
  { name: "Dollar Tree", symbol: "DLTR", risk: 19 },
  { name: "Dominion Energy", symbol: "D", risk: 18 },
  { name: "Dover Corporation", symbol: "DOV", risk: 17 },
  { name: "Dow Inc.", symbol: "DOW", risk: 22 },
  { name: "DTE Energy", symbol: "DTE", risk: 20 },
  { name: "Duke Energy", symbol: "DUK", risk: 19 },
  { name: "DuPont de Nemours", symbol: "DD", risk: 21 },
  { name: "DXC Technology", symbol: "DXC", risk: 22 },
  { name: "Eastman Chemical", symbol: "EMN", risk: 21 },
  { name: "Eaton Corporation", symbol: "ETN", risk: 20 },
  { name: "eBay", symbol: "EBAY", risk: 19 },
  { name: "Ecolab", symbol: "ECL", risk: 18 },
  { name: "Edison International", symbol: "EIX", risk: 19 },
  { name: "Edwards Lifesciences", symbol: "EW", risk: 20 },
  { name: "Electronic Arts", symbol: "EA", risk: 21 },
  { name: "Elevance Health", symbol: "ELV", risk: 19 },
  { name: "Emerson Electric", symbol: "EMR", risk: 18 },
  { name: "Enphase Energy", symbol: "ENPH", risk: 22 },
  { name: "Entergy", symbol: "ETR", risk: 20 },
  { name: "EOG Resources", symbol: "EOG", risk: 23 },
  { name: "EPAM Systems", symbol: "EPAM", risk: 22 },
  { name: "Equifax", symbol: "EFX", risk: 19 },
  { name: "Equinix", symbol: "EQIX", risk: 20 },
  { name: "Equity Residential", symbol: "EQR", risk: 18 },
  { name: "Essex Property Trust", symbol: "ESS", risk: 19 },
  { name: "Estee Lauder", symbol: "EL", risk: 20 },
  { name: "Evergy", symbol: "EVRG", risk: 18 },
  { name: "Everest Re Group", symbol: "RE", risk: 21 },
  { name: "Exelon", symbol: "EXC", risk: 19 },
  { name: "Expedia Group", symbol: "EXPE", risk: 22 },
  { name: "Expeditors International", symbol: "EXPD", risk: 20 },
  { name: "Extra Space Storage", symbol: "EXR", risk: 18 },
  { name: "ExxonMobil", symbol: "XOM", risk: 23 },
  { name: "F5 Networks", symbol: "FFIV", risk: 22 },
  { name: "Fastenal", symbol: "FAST", risk: 19 },
  { name: "Federal Realty", symbol: "FRT", risk: 20 },
  { name: "FedEx", symbol: "FDX", risk: 21 },
  { name: "Fidelity National Information Services", symbol: "FIS", risk: 19 },
  { name: "Fifth Third Bancorp", symbol: "FITB", risk: 18 },
  { name: "First Republic Bank", symbol: "FRC", risk: 21 },
  { name: "First Solar", symbol: "FSLR", risk: 22 },
  { name: "FirstEnergy", symbol: "FE", risk: 20 },
  { name: "Fiserv", symbol: "FISV", risk: 18 },
  { name: "FleetCor Technologies", symbol: "FLT", risk: 21 },
  { name: "Flowserve", symbol: "FLS", risk: 20 },
  { name: "Fluor", symbol: "FLR", risk: 22 },
  { name: "FMC Corporation", symbol: "FMC", risk: 20 },
  { name: "Ford Motor", symbol: "F", risk: 24 },
  { name: "Fortinet", symbol: "FTNT", risk: 21 },
  { name: "Fortive", symbol: "FTV", risk: 20 },
  { name: "Fox Corporation (Class A)", symbol: "FOXA", risk: 21 },
  { name: "Fox Corporation (Class B)", symbol: "FOX", risk: 21 },
  { name: "Franklin Resources", symbol: "BEN", risk: 18 },
  { name: "Freeport-McMoRan", symbol: "FCX", risk: 23 },
  { name: "Garmin", symbol: "GRMN", risk: 19 },
  { name: "Gartner", symbol: "IT", risk: 20 },
  { name: "General Dynamics", symbol: "GD", risk: 19 },
  { name: "General Electric", symbol: "GE", risk: 22 },
  { name: "General Mills", symbol: "GIS", risk: 18 },
  { name: "General Motors", symbol: "GM", risk: 24 },
  { name: "Genuine Parts", symbol: "GPC", risk: 18 },
  { name: "Gilead Sciences", symbol: "GILD", risk: 19 },
  { name: "Globe Life", symbol: "GL", risk: 20 },
  { name: "Goldman Sachs", symbol: "GS", risk: 23 },
  { name: "Halliburton", symbol: "HAL", risk: 21 },
  { name: "Hartford Financial", symbol: "HIG", risk: 19 },
  { name: "Hasbro", symbol: "HAS", risk: 22 },
  { name: "HCA Healthcare", symbol: "HCA", risk: 21 },
  { name: "Healthpeak Properties", symbol: "PEAK", risk: 20 },
  { name: "Henry Schein", symbol: "HSIC", risk: 19 },
  { name: "Hershey", symbol: "HSY", risk: 18 },
  { name: "Hess Corporation", symbol: "HES", risk: 22 },
  { name: "Hewlett Packard Enterprise", symbol: "HPE", risk: 20 },
  { name: "Hilton Worldwide", symbol: "HLT", risk: 22 },
  { name: "Hologic", symbol: "HOLX", risk: 21 },
  { name: "Home Depot", symbol: "HD", risk: 18 },
  { name: "Honeywell", symbol: "HON", risk: 19 },
  { name: "Hormel Foods", symbol: "HRL", risk: 17 },
  { name: "Host Hotels & Resorts", symbol: "HST", risk: 21 },
  { name: "Howmet Aerospace", symbol: "HWM", risk: 20 },
  { name: "HP Inc.", symbol: "HPQ", risk: 19 },
  { name: "Humana", symbol: "HUM", risk: 22 },
  { name: "Huntington Bancshares", symbol: "HBAN", risk: 20 },
  { name: "Huntington Ingalls", symbol: "HII", risk: 21 },
  { name: "IDEX Corporation", symbol: "IEX", risk: 20 },
  { name: "IDEXX Laboratories", symbol: "IDXX", risk: 19 },
  { name: "IHS Markit", symbol: "INFO", risk: 18 },
  { name: "Illinois Tool Works", symbol: "ITW", risk: 19 },
  { name: "Illumina", symbol: "ILMN", risk: 22 },
  { name: "Incyte", symbol: "INCY", risk: 23 },
  { name: "Intel", symbol: "INTC", risk: 20 },
  { name: "Intercontinental Exchange", symbol: "ICE", risk: 18 },
  { name: "International Paper", symbol: "IP", risk: 20 },
  { name: "Interpublic Group", symbol: "IPG", risk: 19 },
  { name: "Intl Flavors & Fragrances", symbol: "IFF", risk: 21 },
  { name: "Intuit", symbol: "INTU", risk: 19 },
  { name: "Invesco", symbol: "IVZ", risk: 20 },
  { name: "IPG Photonics", symbol: "IPGP", risk: 22 },
  { name: "IQVIA", symbol: "IQV", risk: 21 },
  { name: "Iron Mountain", symbol: "IRM", risk: 20 },
  { name: "J.B. Hunt", symbol: "JBHT", risk: 19 },
  { name: "Jack Henry & Associates", symbol: "JKHY", risk: 20 },
  { name: "Jacobs Engineering", symbol: "J", risk: 19 },
  { name: "J.M. Smucker", symbol: "SJM", risk: 20 },
  { name: "Johnson & Johnson", symbol: "JNJ", risk: 12 },
  { name: "Johnson Controls", symbol: "JCI", risk: 20 },
  { name: "JPMorgan Chase", symbol: "JPM", risk: 16 },
  { name: "Juniper Networks", symbol: "JNPR", risk: 21 },
  { name: "Kansas City Southern", symbol: "KSU", risk: 22 },
  { name: "Kellogg's", symbol: "K", risk: 19 },
  { name: "KeyCorp", symbol: "KEY", risk: 18 },
  { name: "Keysight Technologies", symbol: "KEYS", risk: 20 },
  { name: "Kimberly-Clark", symbol: "KMB", risk: 17 },
  { name: "Kimco Realty", symbol: "KIM", risk: 18 },
  { name: "Kinder Morgan", symbol: "KMI", risk: 19 },
  { name: "KLA Corporation", symbol: "KLAC", risk: 21 },
  { name: "Kroger", symbol: "KR", risk: 18 },
  { name: "L3Harris Technologies", symbol: "LHX", risk: 19 },
  { name: "Laboratory Corporation of America", symbol: "LH", risk: 20 },
  { name: "Lam Research", symbol: "LRCX", risk: 21 },
  { name: "Lamb Weston Holdings", symbol: "LW", risk: 19 },
  { name: "Las Vegas Sands", symbol: "LVS", risk: 23 },
  { name: "Leidos", symbol: "LDOS", risk: 20 },
  { name: "Lennar", symbol: "LEN", risk: 21 },
  { name: "Lilly", symbol: "LLY", risk: 18 },
  { name: "Lincoln National", symbol: "LNC", risk: 20 },
  { name: "Linde plc", symbol: "LIN", risk: 19 },
  { name: "Live Nation", symbol: "LYV", risk: 21 },
  { name: "LKQ Corporation", symbol: "LKQ", risk: 19 },
  { name: "Lockheed Martin", symbol: "LMT", risk: 18 },
  { name: "Loews Corporation", symbol: "L", risk: 20 },
  { name: "Lowe's", symbol: "LOW", risk: 19 },
  { name: "Lumen Technologies", symbol: "LUMN", risk: 21 },
  { name: "Lyft", symbol: "LYFT", risk: 22 },
  { name: "M&T Bank", symbol: "MTB", risk: 18 },
  { name: "Marathon Oil", symbol: "MRO", risk: 23 },
  { name: "Marathon Petroleum", symbol: "MPC", risk: 21 },
  { name: "MarketAxess", symbol: "MKTX", risk: 20 },
  { name: "Marriott International", symbol: "MAR", risk: 19 },
  { name: "Marsh & McLennan", symbol: "MMC", risk: 18 },
  { name: "Martin Marietta Materials", symbol: "MLM", risk: 20 },
  { name: "Mastercard", symbol: "MA", risk: 15 },
  { name: "Match Group", symbol: "MTCH", risk: 20 },
  { name: "McCormick & Company", symbol: "MKC", risk: 18 },
  { name: "McDonald's", symbol: "MCD", risk: 17 },
  { name: "McKesson Corporation", symbol: "MCK", risk: 19 },
  { name: "Medtronic", symbol: "MDT", risk: 18 },
  { name: "Merck & Co.", symbol: "MRK", risk: 17 },
  { name: "Meta Platforms", symbol: "META", risk: 22 },
  { name: "MetLife", symbol: "MET", risk: 20 },
  { name: "Mettler-Toledo", symbol: "MTD", risk: 21 },
  { name: "MGM Resorts", symbol: "MGM", risk: 22 },
  { name: "Microchip Technology", symbol: "MCHP", risk: 21 },
  { name: "Micron Technology", symbol: "MU", risk: 20 },
  { name: "Microsoft", symbol: "MSFT", risk: 15 },
  { name: "Mid-America Apartment Communities", symbol: "MAA", risk: 19 },
  { name: "Mohawk Industries", symbol: "MHK", risk: 20 },
  { name: "Molson Coors Beverage", symbol: "TAP", risk: 18 },
  { name: "Mondelez International", symbol: "MDLZ", risk: 19 },
  { name: "MongoDB", symbol: "MDB", risk: 21 },
  { name: "Monster Beverage", symbol: "MNST", risk: 18 },
  { name: "Moody's Corporation", symbol: "MCO", risk: 19 },
  { name: "Morgan Stanley", symbol: "MS", risk: 20 },
  { name: "Motorola Solutions", symbol: "MSI", risk: 19 },
  { name: "MSCI Inc.", symbol: "MSCI", risk: 21 },
  { name: "Nasdaq, Inc.", symbol: "NDAQ", risk: 20 },
  { name: "National Oilwell Varco", symbol: "NOV", risk: 23 },
  { name: "Netflix", symbol: "NFLX", risk: 22 },
  { name: "Newell Brands", symbol: "NWL", risk: 20 },
  { name: "Newmont Corporation", symbol: "NEM", risk: 21 },
  { name: "News Corporation (Class A)", symbol: "NWSA", risk: 20 },
  { name: "News Corporation (Class B)", symbol: "NWS", risk: 20 },
  { name: "NextEra Energy", symbol: "NEE", risk: 19 },
  { name: "Nielsen Holdings", symbol: "NLSN", risk: 20 },
  { name: "Nike", symbol: "NKE", risk: 17 },
  { name: "NiSource", symbol: "NI", risk: 18 },
  { name: "Norfolk Southern", symbol: "NSC", risk: 21 },
  { name: "Northern Trust", symbol: "NTRS", risk: 20 },
  { name: "Northrop Grumman", symbol: "NOC", risk: 19 },
  { name: "NortonLifeLock", symbol: "NLOK", risk: 21 },
  { name: "Norwegian Cruise Line", symbol: "NCLH", risk: 23 },
  { name: "NRG Energy", symbol: "NRG", risk: 22 },
  { name: "Nucor", symbol: "NUE", risk: 20 },
  { name: "Nvidia", symbol: "NVDA", risk: 28 },
  { name: "NVR, Inc.", symbol: "NVR", risk: 20 },
  { name: "Occidental Petroleum", symbol: "OXY", risk: 23 },
  { name: "Omnicom Group", symbol: "OMC", risk: 19 },
  { name: "ON Semiconductor", symbol: "ON", risk: 21 },
  { name: "ONEOK", symbol: "OKE", risk: 21 },
  { name: "Oracle", symbol: "ORCL", risk: 18 },
  { name: "O'Reilly Automotive", symbol: "ORLY", risk: 20 },
  { name: "Otis Worldwide", symbol: "OTIS", risk: 19 },
  { name: "Owens Corning", symbol: "OC", risk: 21 },
  { name: "PACCAR Inc.", symbol: "PCAR", risk: 19 },
  { name: "Packaging Corporation of America", symbol: "PKG", risk: 20 },
  { name: "Palantir Technologies", symbol: "PLTR", risk: 22 },
  { name: "Parker-Hannifin", symbol: "PH", risk: 18 },
  { name: "Paycom", symbol: "PAYC", risk: 20 },
  { name: "PayPal", symbol: "PYPL", risk: 21 },
  { name: "Pentair", symbol: "PNR", risk: 18 },
  { name: "PepsiCo", symbol: "PEP", risk: 15 },
  { name: "PerkinElmer", symbol: "PKI", risk: 20 },
  { name: "Pfizer", symbol: "PFE", risk: 22 },
  { name: "PG&E Corporation", symbol: "PCG", risk: 23 },
  { name: "Philip Morris International", symbol: "PM", risk: 18 },
  { name: "Phillips 66", symbol: "PSX", risk: 22 },
  { name: "Pinnacle West", symbol: "PNW", risk: 19 },
  { name: "Pioneer Natural Resources", symbol: "PXD", risk: 21 },
  { name: "PNC Financial Services", symbol: "PNC", risk: 19 },
  { name: "PNM Resources", symbol: "PNM", risk: 18 },
  { name: "Pool Corporation", symbol: "POOL", risk: 20 },
  { name: "PPG Industries", symbol: "PPG", risk: 21 },
  { name: "PPL Corporation", symbol: "PPL", risk: 18 },
  { name: "Principal Financial Group", symbol: "PFG", risk: 20 },
  { name: "Procter & Gamble", symbol: "PG", risk: 13 },
  { name: "Progressive Corporation", symbol: "PGR", risk: 19 },
  { name: "Prologis", symbol: "PLD", risk: 18 },
  { name: "Prudential Financial", symbol: "PRU", risk: 21 },
  { name: "Public Service Enterprise Group", symbol: "PEG", risk: 19 },
  { name: "Public Storage", symbol: "PSA", risk: 18 },
  { name: "PulteGroup", symbol: "PHM", risk: 20 },
  { name: "Qorvo", symbol: "QRVO", risk: 22 },
  { name: "Qualcomm", symbol: "QCOM", risk: 20 },
  { name: "Quanta Services", symbol: "PWR", risk: 19 },
  { name: "Raymond James Financial", symbol: "RJF", risk: 18 },
  { name: "Raytheon Technologies", symbol: "RTX", risk: 21 },
  { name: "Realty Income", symbol: "O", risk: 18 },
  { name: "Regency Centers", symbol: "REG", risk: 19 },
  { name: "Regeneron Pharmaceuticals", symbol: "REGN", risk: 21 },
  { name: "Regions Financial", symbol: "RF", risk: 18 },
  { name: "Republic Services", symbol: "RSG", risk: 20 },
  { name: "ResMed", symbol: "RMD", risk: 19 },
  { name: "Robert Half", symbol: "RHI", risk: 20 },
  { name: "Rockwell Automation", symbol: "ROK", risk: 19 },
  { name: "Rollins", symbol: "ROL", risk: 18 },
  { name: "Roper Technologies", symbol: "ROP", risk: 20 },
  { name: "Ross Stores", symbol: "ROST", risk: 19 },
  { name: "Royal Caribbean", symbol: "RCL", risk: 22 },
  { name: "S&P Global", symbol: "SPGI", risk: 18 },
  { name: "Salesforce", symbol: "CRM", risk: 19 },
  { name: "SBA Communications", symbol: "SBAC", risk: 21 },
  { name: "Schlumberger", symbol: "SLB", risk: 22 },
  { name: "Sealed Air", symbol: "SEE", risk: 19 },
  { name: "Sempra Energy", symbol: "SRE", risk: 18 },
  { name: "ServiceNow", symbol: "NOW", risk: 21 },
  { name: "Sherwin-Williams", symbol: "SHW", risk: 20 },
  { name: "Simon Property Group", symbol: "SPG", risk: 18 },
  { name: "Skyworks Solutions", symbol: "SWKS", risk: 21 },
  { name: "Snap Inc.", symbol: "SNAP", risk: 23 },
  { name: "SolarEdge Technologies", symbol: "SEDG", risk: 22 },
  { name: "Southern Company", symbol: "SO", risk: 17 },
  { name: "Southwest Airlines", symbol: "LUV", risk: 22 },
  { name: "Stanley Black & Decker", symbol: "SWK", risk: 20 },
  { name: "Starbucks", symbol: "SBUX", risk: 19 },
  { name: "State Street Corporation", symbol: "STT", risk: 18 },
  { name: "STERIS", symbol: "STE", risk: 20 },
  { name: "Stryker Corporation", symbol: "SYK", risk: 18 },
  { name: "SVB Financial", symbol: "SIVB", risk: 20 },
  { name: "Synchrony Financial", symbol: "SYF", risk: 21 },
  { name: "Synopsys", symbol: "SNPS", risk: 19 },
  { name: "Sysco Corporation", symbol: "SYY", risk: 18 },
  { name: "T. Rowe Price", symbol: "TROW", risk: 19 },
  { name: "Take-Two Interactive", symbol: "TTWO", risk: 21 },
  { name: "Tapestry, Inc.", symbol: "TPR", risk: 20 },
  { name: "Target Corporation", symbol: "TGT", risk: 18 },
  { name: "TE Connectivity", symbol: "TEL", risk: 19 },
  { name: "TEGNA", symbol: "TGNA", risk: 21 },
  { name: "Teleflex", symbol: "TFX", risk: 19 },
  { name: "Teradyne", symbol: "TER", risk: 22 },
  { name: "Tesla", symbol: "TSLA", risk: 30 },
  { name: "Texas Instruments", symbol: "TXN", risk: 19 },
  { name: "The Hartford", symbol: "HIG", risk: 19 },
  { name: "The Hershey Company", symbol: "HSY", risk: 18 },
  { name: "The Kraft Heinz Company", symbol: "KHC", risk: 19 },
  { name: "The Mosaic Company", symbol: "MOS", risk: 21 },
  { name: "The Travelers Companies", symbol: "TRV", risk: 20 },
  { name: "Thermo Fisher Scientific", symbol: "TMO", risk: 18 },
  { name: "Tiffany & Co.", symbol: "TIF", risk: 20 },
  { name: "TJX Companies", symbol: "TJX", risk: 18 },
  { name: "Tractor Supply", symbol: "TSCO", risk: 19 },
  { name: "Trane Technologies", symbol: "TT", risk: 21 },
  { name: "TransDigm Group", symbol: "TDG", risk: 22 },
  { name: "TransUnion", symbol: "TRU", risk: 20 },
  { name: "TripAdvisor", symbol: "TRIP", risk: 21 },
  { name: "Truist Financial", symbol: "TFC", risk: 19 },
  { name: "T-Mobile", symbol: "TMUS", risk: 18 },
  { name: "Tyson Foods", symbol: "TSN", risk: 19 },
  { name: "UDR, Inc.", symbol: "UDR", risk: 21 },
  { name: "Ulta Beauty", symbol: "ULTA", risk: 20 },
  { name: "Under Armour (Class A)", symbol: "UAA", risk: 22 },
  { name: "Under Armour (Class C)", symbol: "UA", risk: 22 },
  { name: "Union Pacific", symbol: "UNP", risk: 19 },
  { name: "United Airlines Holdings", symbol: "UAL", risk: 24 },
  { name: "United Parcel Service", symbol: "UPS", risk: 18 },
  { name: "United Rentals", symbol: "URI", risk: 21 },
  { name: "UnitedHealth Group", symbol: "UNH", risk: 18 },
  { name: "Universal Health Services", symbol: "UHS", risk: 21 },
  { name: "Unum Group", symbol: "UNM", risk: 20 },
  { name: "Valero Energy", symbol: "VLO", risk: 23 },
  { name: "Ventas", symbol: "VTR", risk: 19 },
  { name: "Verisk Analytics", symbol: "VRSK", risk: 20 },
  { name: "Verizon", symbol: "VZ", risk: 19 },
  { name: "Vertex Pharmaceuticals", symbol: "VRTX", risk: 22 },
  { name: "VF Corporation", symbol: "VFC", risk: 20 },
  { name: "ViacomCBS (Class A)", symbol: "VIACA", risk: 22 },
  { name: "ViacomCBS (Class B)", symbol: "VIAC", risk: 22 },
  { name: "VICI Properties", symbol: "VICI", risk: 21 },
  { name: "VISA Inc.", symbol: "V", risk: 14 },
  { name: "Vistra Corp.", symbol: "VST", risk: 20 },
  { name: "VMware", symbol: "VMW", risk: 21 },
  { name: "Vornado Realty Trust", symbol: "VNO", risk: 23 },
  { name: "Vulcan Materials", symbol: "VMC", risk: 20 },
  { name: "W. R. Berkley", symbol: "WRB", risk: 19 },
  { name: "Wabtec Corporation", symbol: "WAB", risk: 20 },
  { name: "Walgreens Boots Alliance", symbol: "WBA", risk: 20 },
  { name: "Walmart", symbol: "WMT", risk: 20 },
  { name: "Walt Disney", symbol: "DIS", risk: 20 },
  { name: "Waste Management", symbol: "WM", risk: 19 },
  { name: "Waters Corporation", symbol: "WAT", risk: 21 },
  { name: "WEC Energy Group", symbol: "WEC", risk: 18 },
  { name: "Wells Fargo", symbol: "WFC", risk: 21 },
  { name: "Welltower", symbol: "WELL", risk: 19 },
  { name: "West Pharmaceutical Services", symbol: "WST", risk: 20 },
  { name: "Western Digital", symbol: "WDC", risk: 21 },
  { name: "Western Union", symbol: "WU", risk: 20 },
  { name: "WestRock", symbol: "WRK", risk: 21 },
  { name: "Weyerhaeuser", symbol: "WY", risk: 19 },
  { name: "Whirlpool Corporation", symbol: "WHR", risk: 22 },
  { name: "Williams Companies", symbol: "WMB", risk: 21 },
  { name: "Willis Towers Watson", symbol: "WLTW", risk: 20 },
  { name: "Wynn Resorts", symbol: "WYNN", risk: 24 },
  { name: "Xcel Energy", symbol: "XEL", risk: 18 },
  { name: "Xerox", symbol: "XRX", risk: 22 },
  { name: "Xilinx", symbol: "XLNX", risk: 21 },
  { name: "XPO Logistics", symbol: "XPO", risk: 21 },
  { name: "Yum! Brands", symbol: "YUM", risk: 19 },
  { name: "Zimmer Biomet", symbol: "ZBH", risk: 20 },
  { name: "Zions Bancorp", symbol: "ZION", risk: 21 },
  { name: "Zoetis", symbol: "ZTS", risk: 19 }
];

